name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: GH_TOKEN
          script: |
            export GITHUB_TOKEN=$GH_TOKEN
            git clone git@github.com:ResamVi/awesome-java-stars.git repo
            docker-compose -p awesomejava -f repo/docker-compose.yml down
            docker-compose -p awesomejava -f repo/docker-compose.yml up --detach --build --force-recreate
            rm -rf repo
